/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define CONFIGURATION "-Dlibmpv=true -Dgl=enabled -Dplain-gl=enabled -Diconv=enabled -Duchardet=enabled -Dvulkan=enabled -Dmoltenvk=enabled -Djavascript=disabled -Dzimg=disabled -Djpeg=disabled -Dvapoursynth=disabled -Drubberband=disabled -Dgpl=true -Dlibbluray=enabled '-Dswift-flags=-sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.5.sdk -target arm64-apple-macos12.0' -Dcocoa=enabled -Dcoreaudio=enabled -Davfoundation=enabled -Dgl-cocoa=enabled -Dvideotoolbox-gl=enabled -Dvideotoolbox-pl=enabled -Dlua=disabled --cross-file=/Users/truls.aagedal/Developer/MPVKit/dist/libmpv/macos/scratch/arm64/crossFile.meson"

#define DEFAULT_OPTICAL_DEVICE "/dev/disk1"

#define FULLCONFIG "avfoundation bsd-fstatfs build-date cocoa coreaudio cplugins darwin ffmpeg gl gl-cocoa glob glob-posix gpl iconv lcms2 libass libavdevice libbluray libdl libplacebo mac-thread-name macos-10-15-4-features macos-11-3-features macos-11-features macos-12-features macos-cocoa-cb macos-media-player macos-touchbar moltenvk posix posix-shm swift uchardet vector videotoolbox-gl videotoolbox-pl vulkan zlib"

#define HAVE_AAUDIO 0

#define HAVE_ALSA 0

#define HAVE_ANDROID 0

#define HAVE_ANDROID_MEDIA_NDK 0

#define HAVE_AUDIOTRACK 0

#define HAVE_AUDIOUNIT 0

#define HAVE_AVFOUNDATION 1

#define HAVE_BSD_FSTATFS 1

#define HAVE_BSD_THREAD_NAME 0

#define HAVE_BUILD_DATE 1

#define HAVE_CACA 0

#define HAVE_CDDA 0

#define HAVE_COCOA 1

#define HAVE_CONSIO_H 0

#define HAVE_COREAUDIO 1

#define HAVE_CPLUGINS 1

#define HAVE_CUDA_HWACCEL 0

#define HAVE_CUDA_INTEROP 0

#define HAVE_D3D11 0

#define HAVE_D3D9_HWACCEL 0

#define HAVE_D3D_HWACCEL 0

#define HAVE_DARWIN 1

#define HAVE_DEBUG 0

#define HAVE_DIRECT3D 0

#define HAVE_DISABLE_PACKET_POOL 0

#define HAVE_DMABUF_INTEROP_GL 0

#define HAVE_DMABUF_WAYLAND 0

#define HAVE_DOS_PATHS 0

#define HAVE_DRM 0

#define HAVE_DVBIN 0

#define HAVE_DVDNAV 0

#define HAVE_EGL 0

#define HAVE_EGL_ANDROID 0

#define HAVE_EGL_ANGLE 0

#define HAVE_EGL_ANGLE_LIB 0

#define HAVE_EGL_ANGLE_WIN32 0

#define HAVE_EGL_DRM 0

#define HAVE_EGL_WAYLAND 0

#define HAVE_EGL_X11 0

#define HAVE_FFMPEG 1

#define HAVE_FFNVCODEC 0

#define HAVE_GBM 0

#define HAVE_GL 1

#define HAVE_GLIBC_THREAD_NAME 0

#define HAVE_GLOB 1

#define HAVE_GLOB_POSIX 1

#define HAVE_GLOB_WIN32 0

#define HAVE_GL_COCOA 1

#define HAVE_GL_DXINTEROP 0

#define HAVE_GL_DXINTEROP_D3D9 0

#define HAVE_GL_WIN32 0

#define HAVE_GL_X11 0

#define HAVE_GPL 1

#define HAVE_ICONV 1

#define HAVE_IOS_GL 0

#define HAVE_JACK 0

#define HAVE_JAVASCRIPT 0

#define HAVE_JPEG 0

#define HAVE_LCMS2 1

#define HAVE_LIBARCHIVE 0

#define HAVE_LIBASS 1

#define HAVE_LIBAVDEVICE 1

#define HAVE_LIBBLURAY 1

#define HAVE_LIBDL 1

#define HAVE_LIBPLACEBO 1

#define HAVE_LINUX_FSTATFS 0

#define HAVE_LUA 0

#define HAVE_MACOS_10_15_4_FEATURES 1

#define HAVE_MACOS_11_3_FEATURES 1

#define HAVE_MACOS_11_FEATURES 1

#define HAVE_MACOS_12_FEATURES 1

#define HAVE_MACOS_COCOA_CB 1

#define HAVE_MACOS_MEDIA_PLAYER 1

#define HAVE_MACOS_TOUCHBAR 1

#define HAVE_MAC_THREAD_NAME 1

#define HAVE_MEMFD_CREATE 0

#define HAVE_MEMRCHR 0

#define HAVE_MOLTENVK 1

#define HAVE_OPENAL 0

#define HAVE_OPENSLES 0

#define HAVE_OSS_AUDIO 0

#define HAVE_PIPEWIRE 0

#define HAVE_POSIX 1

#define HAVE_POSIX_SHM 1

#define HAVE_PPOLL 0

#define HAVE_PTHREAD_CONDATTR_SETCLOCK 0

#define HAVE_PTHREAD_DEBUG 0

#define HAVE_PULSE 0

#define HAVE_RUBBERBAND 0

#define HAVE_SDL2_AUDIO 0

#define HAVE_SDL2_GAMEPAD 0

#define HAVE_SDL2_VIDEO 0

#define HAVE_SHADERC 0

#define HAVE_SIXEL 0

#define HAVE_SNDIO 0

#define HAVE_SNDIO_1_9 0

#define HAVE_SPIRV_CROSS 0

#define HAVE_SWIFT 1

#define HAVE_UCHARDET 1

#define HAVE_UWP 0

#define HAVE_VAAPI 0

#define HAVE_VAAPI_DRM 0

#define HAVE_VAAPI_WAYLAND 0

#define HAVE_VAAPI_WIN32 0

#define HAVE_VAAPI_X11 0

#define HAVE_VAPOURSYNTH 0

#define HAVE_VDPAU 0

#define HAVE_VDPAU_GL_X11 0

#define HAVE_VECTOR 1

#define HAVE_VIDEOTOOLBOX_GL 1

#define HAVE_VIDEOTOOLBOX_PL 1

#define HAVE_VK_KHR_DISPLAY 0

#define HAVE_VT_H 0

#define HAVE_VULKAN 1

#define HAVE_WASAPI 0

#define HAVE_WAYLAND 0

#define HAVE_WIN32 0

#define HAVE_WIN32_DESKTOP 0

#define HAVE_WIN32_EXECUTABLE 0

#define HAVE_WIN32_SMTC 0

#define HAVE_WIN32_THREADS 0

#define HAVE_WSDISPLAY_USL_IO_H 0

#define HAVE_X11 0

#define HAVE_X11_CLIPBOARD 0

#define HAVE_XV 0

#define HAVE_ZIMG 0

#define HAVE_ZLIB 1

#define MPV_CONFDIR "/Users/truls.aagedal/Developer/MPVKit/dist/libmpv/macos/thin/arm64/etc/mpv"

#define PLATFORM "darwin"

