// Aagedal Media Converter
// Copyright 2025 Truls Aagedal
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

import Foundation

/// Encapsulates all data needed to perform a single FFMPEG conversion.
/// Callbacks (progressUpdate, completion) are passed separately.
struct ConversionRequest: Sendable {
    // MARK: - Input / Output
    let inputURL: URL
    let outputURL: URL
    let preset: ExportPreset

    // MARK: - Metadata
    var comment: String = ""
    var includeDateTag: Bool = true
    var sourceMetadata: VideoMetadata? = nil
    var sourceCameraMetadata: CameraMetadata? = nil
    var dcpMetadata: DCPItemMetadata? = nil
    var imfMetadata: IMFItemMetadata? = nil

    // MARK: - Trim & Timing
    var trimStart: Double? = nil
    var trimEnd: Double? = nil
    var expectedDuration: Double? = nil
    var videoFrameRate: Double? = nil

    // MARK: - Processing Configuration
    var audioRoutingConfig: AudioRoutingConfig? = nil
    var cropConfig: CropConfig? = nil
    var timecodeConfig: TimecodeConfig? = nil
    var isMuted: Bool = false

    // MARK: - Special Rendering
    var waveformRequest: WaveformVideoRequest? = nil
    var synthesizedVideoRequest: SynthesizedVideoRequest? = nil
    var waveformBackgroundImageURL: URL? = nil

    /// A representative visual input used for geometry inspection when `inputURL`
    /// is a virtual source such as an image-sequence directory.
    var visualSourceURL: URL? = nil

    // MARK: - FFMPEG Argument Overrides
    var customInputArguments: [String]? = nil
    var additionalOutputArguments: [String]? = nil
}

/// Owns the input boundaries of the app's generated sources. Unknown argument forms
/// retain their original ordering through the compatibility case.
enum FFMPEGInputPlan: Equatable, Sendable {
    case file(URL)
    case imageSequence(pattern: String, frameRate: String, startNumber: String?, audioPath: String?)
    case concat(path: String, safe: String)
    case custom([String])

    init(inputURL: URL, customArguments: [String]?) {
        guard let customArguments else {
            self = .file(inputURL)
            return
        }
        // Recognize only complete forms generated by this app. A token appearing
        // in an arbitrary option value must not change source classification.
        var index = 0
        if customArguments.count >= 4, customArguments[0] == "-framerate" {
            let rate = customArguments[1]
            index = 2
            var startNumber: String?
            if customArguments[index] == "-start_number", index + 1 < customArguments.count {
                startNumber = customArguments[index + 1]
                index += 2
            }
            if index + 1 < customArguments.count, customArguments[index] == "-i" {
                let pattern = customArguments[index + 1]
                index += 2
                if index == customArguments.count {
                    self = .imageSequence(pattern: pattern, frameRate: rate, startNumber: startNumber, audioPath: nil)
                    return
                }
                if index + 2 == customArguments.count, customArguments[index] == "-i" {
                    self = .imageSequence(pattern: pattern, frameRate: rate, startNumber: startNumber,
                                          audioPath: customArguments[index + 1])
                    return
                }
            }
        }
        if customArguments.count == 6,
           Array(customArguments.prefix(3)) == ["-f", "concat", "-safe"],
           customArguments[4] == "-i" {
            self = .concat(path: customArguments[5], safe: customArguments[3])
            return
        }
        self = .custom(customArguments)
    }

    var isImageSequence: Bool {
        if case .imageSequence = self { return true }
        return false
    }

    var companionAudioPath: String? {
        if case .imageSequence(_, _, _, let audioPath) = self { return audioPath }
        return nil
    }

    var imageSequenceFrameRate: String? {
        if case .imageSequence(_, let frameRate, _, _) = self { return frameRate }
        return nil
    }

    /// Input seeks belong to each independently opened timeline. The companion
    /// audio of an image sequence must advance by the same amount as its frames.
    /// Default-file options (such as DCP color hints) never leak to custom sources.
    func arguments(seek: [String] = [], fileOptions: [String] = []) -> [String] {
        switch self {
        case .file(let url):
            return seek + fileOptions + ["-i", url.path]
        case .imageSequence(let pattern, let frameRate, let startNumber, let audioPath):
            var arguments = seek + ["-framerate", frameRate]
            if let startNumber { arguments += ["-start_number", startNumber] }
            arguments += ["-i", pattern]
            if let audioPath { arguments += seek + ["-i", audioPath] }
            return arguments
        case .concat(let path, let safe):
            return seek + ["-f", "concat", "-safe", safe, "-i", path]
        case .custom(let arguments):
            return seek + arguments
        }
    }
}
